export const ACTION_TYPES = {
    //App loader actions
    ENABLE_APP_LOADER: 'ENABLE_APP_LOADER',
    DISABLE_APP_LOADER: 'DISABLE_APP_LOADER',

    //App language available actions
    GET_AVL_LANGUAGES_LIST: 'GET_AVL_LANGUAGES_LIST',
    GET_AVL_LANGUAGES_PENDING: 'GET_AVL_LANGUAGES_PENDING',
    GET_AVL_LANGUAGES_SUCCESS: 'GET_AVL_LANGUAGES_SUCCESS',
    GET_AVL_LANGUAGES_ERROR: 'GET_AVL_LANGUAGES_ERROR',

    SELECT_DEFAULT_APP_LANG: 'SELECT_DEFAULT_APP_LANG',
    UPDATE_DEFAULT_APP_LANG: 'UPDATE_DEFAULT_APP_LANG',
    DELETE_DEFAULT_APP_LANG: 'DELETE_DEFAULT_APP_LANG',
};


export const ROUTE_NAMES = {
    INITIAL_GET_STARTED: 'GetStarted',
    LANGUAGE_SELECTION: 'languageSelection',
    USER_LOGIN: 'UserLogin'

};


export const FIREBASE_DOCUMENT_NAMES = {
    AVAILABLE_APP_LANGUAGES: 'app_languages',
    LOGIN_OR_SIGNUP_SCR:'LoginOrSignup_Scr',
};
