export const ACTION_TYPES = {
    GET_AVL_LANGUAGES_LIST: 'GET_AVL_LANGUAGES_LIST',
    GET_AVL_LANGUAGES_PENDING: 'GET_AVL_LANGUAGES_PENDING',
    GET_AVL_LANGUAGES_SUCCESS: 'GET_AVL_LANGUAGES_SUCCESS',
    GET_AVL_LANGUAGES_ERROR: 'GET_AVL_LANGUAGES_ERROR',
}