export const ACTION_TYPES = {
    //App loader actions
    ENABLE_APP_LOADER: 'ENABLE_APP_LOADER',
    DISABLE_APP_LOADER: 'DISABLE_APP_LOADER',

    //App language available actions
    GET_AVL_LANGUAGES_LIST: 'GET_AVL_LANGUAGES_LIST',
    GET_AVL_LANGUAGES_PENDING: 'GET_AVL_LANGUAGES_PENDING',
    GET_AVL_LANGUAGES_SUCCESS: 'GET_AVL_LANGUAGES_SUCCESS',
    GET_AVL_LANGUAGES_ERROR: 'GET_AVL_LANGUAGES_ERROR',
}


export const ROUTE_NAMES = {
    INITIAL_GET_STARTED: 'GetStarted',
    LANGUAGE_SELECTION_SCREEN: 'languageSelectionScreen',

}